name: istory
description: Interactive moral stories for children
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  just_audio: ^0.10.5
  http: ^1.2.2
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.0
  path_provider: ^2.1.4
  audioplayers: ^6.0.0

flutter:
  uses-material-design: true
