spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

openai:
  base-url: https://api.openai.com/v1
  api-key:
  model: gpt-4.1
  timeout-seconds: 30
  api:
    key:
      tts:
    model: gpt-4o-mini-tts

logging:
  level:
    root: INFO
    com.istory.storyengine: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: WARN


